--desc v$sql_plan
--select * from gv$sql_plan where SQL_ID = 'd5h2xv39zrt77'
--select * from dict
--where table_name like '%BIND%'
--desc GV$SQL_BIND_CAPTURE 
--select * from GV$SQL_BIND_CAPTURE where SQL_ID = 'd5h2xv39zrt77' and child_number = 4 
--000000030A1C91C0

SELECT 
--GV$SQL_PLAN.*, 
GV$SQL_BIND_CAPTURE.*
  FROM GV$SQL_PLAN, GV$SQL_BIND_CAPTURE
 WHERE     (GV$SQL_PLAN.INST_ID = GV$SQL_BIND_CAPTURE.INST_ID)
       AND (GV$SQL_PLAN.ADDRESS = GV$SQL_BIND_CAPTURE.ADDRESS)
       AND (GV$SQL_PLAN.HASH_VALUE = GV$SQL_BIND_CAPTURE.HASH_VALUE)
       AND (GV$SQL_PLAN.SQL_ID = GV$SQL_BIND_CAPTURE.SQL_ID)
       AND (GV$SQL_PLAN.CHILD_ADDRESS = GV$SQL_BIND_CAPTURE.CHILD_ADDRESS)
       AND (GV$SQL_PLAN.CHILD_NUMBER = GV$SQL_BIND_CAPTURE.CHILD_NUMBER)
       AND (GV$SQL_PLAN.TIMESTAMP = (SELECT max(TIMESTAMP) FROM GV$SQL_PLAN SP WHERE SP.SQL_ID = 'd5h2xv39zrt77'))
       AND (GV$SQL_PLAN.SQL_ID = 'd5h2xv39zrt77')
--ORDER BY  GV$SQL_PLAN.SQL_ID      
       
       